### ISSUE TITLE
Switching hash_bucket into defaultdict(list)

### ISSUE THREAD

**Issue by corona10** [nexB/scancode-toolkit-contrib#3]
Now, `hash_bucket` in `src/samecode/halohash.py` is using [dict](https://github.com/nexB/scancode-toolkit-contrib/blob/master/src/samecode/halohash.py#L300).
But to avoid check `KeyError` every time, it is reasonable to use defaultdict(list) for `hash_bucket` in this case.

**Comment by pombredanne** [comment]
sure, but you have to always be careful with defaultdict as this may have unexpected behavior exactly when you expect a key to be not found. Unless this about the PR you submitted as #2 which was effectively a good usage of this data structure

**Comment by pombredanne** [comment]
Fixed with #2. Thanks!
